CREATE DATABASE IF NOT EXISTS restaurante CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;
USE restaurante;

CREATE TABLE IF NOT EXISTS menu (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    precio DECIMAL(10, 2) NOT NULL,
    fecha_creacion DATE DEFAULT CURRENT_DATE NOT NULL,
    imagen_url VARCHAR(255) NULL
); 

